export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header className="bg-blue-400 p-4">
        <p className="">Header</p>
      </header>

        {children}
        
      <footer className="bg-blue-700 p-4">
        <p>Footer</p>
      </footer>
        </body>
    </html>
  )
}
